"""Bundled sample leads so the app produces results without API keys."""

SAMPLE_LEADS = [
    {
        "business_name": "Bella's Trattoria",
        "category": "Italian Restaurant",
        "address": "412 Mulberry St, Brooklyn, NY 11211",
        "phone": "(718) 555-0142",
        "email": None,
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Bellas+Trattoria+Brooklyn",
        "source": "sample",
    },
    {
        "business_name": "Pop's Auto Repair",
        "category": "Auto Repair Shop",
        "address": "88 Industrial Rd, Newark, NJ 07105",
        "phone": "(973) 555-0177",
        "email": "pops.auto@gmail.com",
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Pops+Auto+Repair+Newark",
        "source": "sample",
    },
    {
        "business_name": "Sunshine Daycare",
        "category": "Childcare",
        "address": "1205 Maple Ave, Austin, TX 78704",
        "phone": "(512) 555-0193",
        "email": None,
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Sunshine+Daycare+Austin",
        "source": "sample",
    },
    {
        "business_name": "Tom's Plumbing & Heating",
        "category": "Plumber",
        "address": "27 Oak St, Portland, ME 04101",
        "phone": "(207) 555-0118",
        "email": "tom@tomsplumbing.local",
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Toms+Plumbing+Portland+ME",
        "source": "sample",
    },
    {
        "business_name": "Greta's Bakery",
        "category": "Bakery",
        "address": "55 Front St, Charleston, SC 29401",
        "phone": "(843) 555-0166",
        "email": None,
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Gretas+Bakery+Charleston",
        "source": "sample",
    },
    {
        "business_name": "Cedar Mountain Landscaping",
        "category": "Landscaping",
        "address": "9 Hilltop Dr, Asheville, NC 28801",
        "phone": "(828) 555-0124",
        "email": None,
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Cedar+Mountain+Landscaping+Asheville",
        "source": "sample",
    },
    {
        "business_name": "Lucky Cat Tattoo",
        "category": "Tattoo Parlor",
        "address": "318 Belmont Ave, Chicago, IL 60657",
        "phone": "(773) 555-0188",
        "email": "luckycat@protonmail.com",
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Lucky+Cat+Tattoo+Chicago",
        "source": "sample",
    },
    {
        "business_name": "Maria's House Cleaning",
        "category": "Cleaning Service",
        "address": "2104 Cesar Chavez St, San Francisco, CA 94110",
        "phone": "(415) 555-0149",
        "email": None,
        "has_website": False,
        "google_maps_url": "https://maps.google.com/?q=Marias+House+Cleaning+San+Francisco",
        "source": "sample",
    },
]
